-- PART 1: Customer & Inventory Filtering
-- Business Requirement: The marketing and inventory teams want to identify customer acquisition trends and inventory risks.
-- 
CREATE DATABASE IF NOT EXISTS ecommerce_interview;
USE ecommerce_interview;

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    country VARCHAR(50),
    signup_date DATE
);


CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30),
    payment_method VARCHAR(30),

    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);
-- VIEW DATA
SELECT * FROM customers;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;

#CREATE DATABASE IF NOT EXISTS ecommerce_interview;
USE ecommerce_interview;

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    country VARCHAR(50),
    signup_date DATE
);


CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30),
    payment_method VARCHAR(30),

    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);
-- VIEW DATA
SELECT * FROM customers;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;



CREATE DATABASE IF NOT EXISTS ecommerce_interview;
USE ecommerce_interview;

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    country VARCHAR(50),
    signup_date DATE
);


CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30),
    payment_method VARCHAR(30),

    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);
-- VIEW DATA
SELECT * FROM customers;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;

-- Show all customers from Bengaluru.
SELECT CUSTOMER_NAME,CITY FROM customers
WHERE CITY="Bengaluru";


-- Q2. Show customers who signed up after ‘2025-01-01’.
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY, SIGNUP_DATE FROM customers
WHERE SIGNUP_DATE>"2025-01-01";

-- Q3. Find customers from Mumbai OR Hyderabad.
SELECT CUSTOMER_NAME,CITY FROM customers
WHERE CITY="Mumbai" OR CITY="Hyderabad";

-- Q4 Show products belonging to the Electronics category.
SELECT * FROM PRODUCTS 
WHERE category="Electronics";

-- Q5. Find products priced above 40000.
SELECT * FROM PRODUCTS 
WHERE PRICE>40000;

-- Q6. Show products where stock is less than 20.
SELECT * FROM PRODUCTS 
WHERE STOCK<20;

-- Q7. Find products with stock between 50 and 100.

SELECT * FROM PRODUCTS 
WHERE STOCK BETWEEN 50 AND 100;

-- Q8. Show customers whose names start with ‘A’.
SELECT customer_name FROM customers
WHERE customer_name LIKE "A%";

-- Q9. Find products whose names contain ‘Premium’.

SELECT * FROM PRODUCTS
WHERE PRODUCT_NAME LIKE "%Premium%";

-- Q10. Show customers registered during the year 2025.

SELECT * FROM CUSTOMERS
WHERE YEAR(SIGNUP_DATE)=2025;

-- PART 2: Revenue & Sales Analysis
-- Business Requirement: The finance department wants summarized revenue and sales insights.

-- Q11. Find total revenue generated by each category.

SELECT CATEGORY,SUM(PRICE) AS TOTAL_REVENUE FROM PRODUCTS
GROUP BY CATEGORY ;

-- Q12. Find total quantity sold for each product.

SELECT P.PRODUCT_NAME,SUM(O.QUANTITY) AS TOTAL_QUANTITY FROM order_items AS O
INNER JOIN products AS P
ON P.product_id=O.ORDER_ID
GROUP BY product_name;

-- Q13. Find total orders under each order status

SELECT STATUS,COUNT(ORDER_ID) TOTAL_ORDERS FROM ORDERS
GROUP BY STATUS;

-- Q14. Find total revenue generated through each payment method.

SELECT O.PAYMENT_METHOD,SUM(P.PRICE) AS TOTAL_REVENUE FROM ORDERS AS O
JOIN ORDER_ITEMS AS IO
ON O.ORDER_ID=IO.ORDER_ID
JOIN PRODUCTS AS P
ON P.PRODUCT_ID=IO.PRODUCT_ID
GROUP BY O.PAYMENT_METHOD
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

-- Q15. Find average product price category-wise.

SELECT CATEGORY,AVG(PRICE) AS AVERAGE_PRICE FROM PRODUCTS 
GROUP BY CATEGORY;

-- Q16. Find category-wise quantity sold.

SELECT P.CATEGORY ,COUNT(O.QUANTITY) AS QUANTITY_SOLD FROM products AS P
INNER JOIN order_items AS O
ON P.PRODUCT_ID=O.PRODUCT_ID
GROUP BY P.CATEGORY;

-- Q17. Find monthly order count.
SELECT month(o.order_date) as monthly_sales,COUNT(distinct io.ORDER_ID) as MONTHLY_ORDER_COUNT FROM ORDERS as o
inner join order_items as io
on o.order_id=io.order_id
group by  month(o.order_date);

-- Q18. Find monthly revenue trend.

SELECT MONTH(O.ORDER_DATE) AS MONTHLY_SALES,SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE
FROM ORDERS AS O JOIN ORDER_ITEMS AS OI
ON O.ORDER_ID =OI.ORDER_ID
GROUP BY MONTH(O.ORDER_DATE);

-- Q19. Find the most commonly used payment method.
SELECT PAYMENT_METHOD,COUNT(PAYMENT_METHOD) AS MOST_COMMON_PAYMENT FROM ORDERS
GROUP BY PAYMENT_METHOD
ORDER BY MOST_COMMON_PAYMENT DESC ;

-- Q20. Find the highest revenue-generating category.
SELECT CATEGORY,MAX(PRICE) AS HIGHEST_REVENUE FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY HIGHEST_REVENUE DESC
LIMIT 1;

-- PART 3: High-Value Business Insights
-- Business Requirement: Management wants to identify high-performing customers, products, and regions.

-- Q21. Find customers who placed more than 5 orders.

SELECT C.CUSTOMER_NAME,COUNT(OI.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMERS AS C INNER JOIN ORDERS AS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
JOIN  ORDER_ITEMS AS OI
ON O.ORDER_ID=OI.ORDER_ID
GROUP BY C.CUSTOMER_NAME ;

-- Q22. Find top 5 customers based on total spending.

SELECT C.CUSTOMER_NAME, SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_SPEND_AMOUNT FROM
 ORDER_ITEMS AS OI INNER JOIN ORDERS AS O
 ON OI.ORDER_ID=O.ORDER_ID
 INNER JOIN CUSTOMERS AS C
 ON C.CUSTOMER_ID=O.CUSTOMER_ID
 GROUP BY CUSTOMER_NAME
 ORDER BY TOTAL_SPEND_AMOUNT DESC
 LIMIT 5;
 
 -- Q23. Find products sold more than 30 times.
 SELECT P.PRODUCT_NAME,SUM(OI.QUANTITY) AS TOTAL_SOLD FROM PRODUCTS AS P
 INNER JOIN ORDER_ITEMS AS OI
 ON P.PRODUCT_ID=OI.PRODUCT_ID
 GROUP BY P.PRODUCT_NAME
 HAVING TOTAL_SOLD>30;

 -- Q24. Find categories generating revenue greater than 50000.
 SELECT CATEGORY,SUM(PRICE) AS TOTAL_REVENUE FROM PRODUCTS
 GROUP BY CATEGORY
 HAVING TOTAL_REVENUE>50000;
 
 -- Q25. Find cities having more than 10 customers.
 SELECT C.CITY,COUNT(O.CUSTOMER_ID) AS COUNT_CUSTOMERS
 FROM CUSTOMERS AS C INNER JOIN ORDERS AS O
 ON C.CUSTOMER_ID=O.CUSTOMER_ID
 GROUP BY C.CITY
 HAVING COUNT_CUSTOMERS>10;
 
-- Q26. Find the top 5 highest-selling products.
SELECT P.PRODUCT_NAME, COUNT(OI.PRODUCT_ID) AS TOP5_PRODUCTS
FROM PRODUCTS AS P INNER JOIN ORDER_ITEMS AS OI
ON P.PRODUCT_ID=OI.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOP5_PRODUCTS DESC
LIMIT 5 ;

-- Q27. Find the top 3 most profitable products.
SELECT PRODUCT_NAME,SUM(PRICE) AS TOP3_PROFITABLE_PRODUCTS
FROM PRODUCTS
GROUP BY PRODUCT_NAME
ORDER BY  TOP3_PROFITABLE_PRODUCTS DESC
LIMIT 3;

-- Q28. Find customers whose spending is above average customer spending.
SELECT C.CUSTOMER_NAME, SUM((OI.QUANTITY * OI.UNIT_PRICE)) AS TOTAL_SPENDING
FROM ORDER_ITEMS AS OI INNER JOIN ORDERS AS O
ON OI.ORDER_ID=O.ORDER_ID
INNER JOIN CUSTOMERS AS C
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
HAVING TOTAL_SPENDING >
(
SELECT AVG(customer_total)
FROM
(
 SELECT SUM(OI.QUANTITY * OI.UNIT_PRICE) AS customer_total
	FROM ORDER_ITEMS AS OI INNER JOIN ORDERS AS O
	ON OI.ORDER_ID = O.ORDER_ID
	GROUP BY O.CUSTOMER_ID
    ) AS avg_table
);

-- Q29. Find products contributing more than 10% of company revenue.

SELECT PRODUCT_NAME,SUM(PRICE) AS PRODUCT_REVENUE FROM PRODUCTS
GROUP BY PRODUCT_NAME
HAVING SUM(PRICE)>(
SELECT SUM(PRICE)*0.10 FROM PRODUCTS
);

-- Q30. Find the city generating the highest revenue.
SELECT C.CITY, SUM(OI.QUANTITY * OI.UNIT_PRICE) AS TOTAL_REVENUE FROM ORDER_ITEMS AS OI INNER JOIN ORDERS AS O
ON O.ORDER_ID=OI.ORDER_ID
INNER JOIN CUSTOMERS AS C
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CITY
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;


